export const DAILY_QUOTES: string[] = [
  'Small progress is still progress.',
  'Done is better than perfect.',
  'Consistency beats intensity.',
  'The hardest part is starting.',
  'The best time to begin is now.',
  'One step, then the next.',
  'Start where you are.',
  'Make it easy to begin.',
  'If it takes less than two minutes, do it now.',
  'You don’t need motivation. You need a plan.',
  'Keep it simple. Keep it moving.',
  'Focus on the next right thing.',
  'Make today a little lighter.',
  'Progress over polish.',
  'Take the win, however small.',
  'Do the obvious thing.',
  'A little effort, consistently, adds up.',
  'Reduce friction, increase follow-through.',
  'Make it boring and repeatable.',
  'Ship the first draft.',
  'Show up for ten minutes.',
  'Less scrolling, more creating.',
  'Pick one thing and finish it.',
  'Finish the loop.',
  'Move the needle.',
  'Keep your promises to yourself.',
  'Start small. Stay steady.',
  'Today counts.',
  'Save your energy for what matters.',
  'You can do hard things—quietly.',
  'Clarity creates momentum.',
  'Make space. Then do the work.',
  'Do it with care, not drama.',
  'A calm plan beats a rushed one.',
  'You’re allowed to be a beginner.',
  'Make it good enough, then make it better.',
  'Do fewer things, better.',
  'Work the plan.',
  'Protect your attention.',
  'Slow is smooth. Smooth is fast.',
  'You don’t need more time. You need fewer distractions.',
  'Make it simple enough to repeat.',
  'Momentum is built, not found.',
  'Do it once, then automate it later.',
  'Start before you feel ready.',
  'If you can do it in 5 minutes, do it now.',
  'The future you will thank you.',
  'No zero days.',
  'Make the next action obvious.',
  'Keep the bar low for starting.',
  'Finish strong, then rest.',
  'You’re closer than you think.',
  'Good work, quietly done.',
  'Make it workable, not perfect.',
  'Turn intention into action.',
  'Your attention is expensive—spend it well.',
  'Less talk, more traction.'
]

export function quoteForDate(date = new Date()): string {
  const key = `${date.getFullYear()}-${date.getMonth() + 1}-${date.getDate()}`
  // simple stable hash
  let hash = 0
  for (let i = 0; i < key.length; i++) hash = (hash * 31 + key.charCodeAt(i)) >>> 0
  return DAILY_QUOTES[hash % DAILY_QUOTES.length]
}
