'use client'
import { useState } from 'react'
import { AppShell } from '@/components/app-shell'
import { Button } from '@/components/ui/button'
import { Card } from '@/components/ui/card'
import { useWorkspace } from '@/lib/workspace-provider'

export default function TasksPage() {
  const { activeTasks, archivedTasks, addTask, toggleTask, updateTask, deleteTask, archiveTask, restoreTask } = useWorkspace()
  const [draft, setDraft] = useState('')
  return <AppShell><div className="page-intro"><p className="eyebrow">Workspace · Tasks</p><h1>Tasks</h1><p className="lede">Capture what matters, then give it your full attention.</p></div><Card className="tasks"><form className="task-form" onSubmit={async (e) => { e.preventDefault(); if (await addTask(draft)) setDraft('') }}><input value={draft} onChange={(e) => setDraft(e.target.value)} placeholder="Add a task…" aria-label="New task"/><Button type="submit">Create task</Button></form>{activeTasks.length ? activeTasks.map((task) => <div className="task-row" key={task.id}><div className="task"><input type="checkbox" checked={task.done} onChange={() => toggleTask(task.id)} aria-label={`Complete ${task.title}`}/><input className="task-edit" value={task.title} onChange={(e) => updateTask(task.id, { title: e.target.value })} aria-label="Task title"/><select value={task.priority} onChange={(e) => updateTask(task.id, { priority: e.target.value as 'low'|'medium'|'high' })} aria-label="Priority"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option></select><button className="text-button" onClick={() => archiveTask(task.id)}>Archive</button><button className="text-button danger" onClick={() => deleteTask(task.id)}>Delete</button></div><details className="task-details"><summary>Details</summary><div className="details-grid"><label>Due date<input type="date" value={task.dueDate || ''} onChange={(e) => updateTask(task.id, { dueDate: e.target.value })}/></label><label>Category<input value={task.category || ''} onChange={(e) => updateTask(task.id, { category: e.target.value })}/></label><label>Tags<input value={task.tags.join(', ')} onChange={(e) => updateTask(task.id, { tags: e.target.value.split(',').map((tag) => tag.trim()).filter(Boolean) })}/></label><label>Notes<textarea value={task.notes || ''} onChange={(e) => updateTask(task.id, { notes: e.target.value })}/></label></div><div className="subtasks"><strong>Subtasks</strong>{task.subtasks.map((subtask) => <label className="task" key={subtask.id}><input type="checkbox" checked={subtask.done} onChange={() => updateTask(task.id, { subtasks: task.subtasks.map((item) => item.id === subtask.id ? { ...item, done: !item.done } : item) })}/><span>{subtask.title}</span></label>)}<button className="text-button" onClick={() => { const title = window.prompt('Subtask name'); if (title?.trim()) updateTask(task.id, { subtasks: [...task.subtasks, { id: String(Date.now()), title: title.trim(), done: false }] }) }}>+ Add subtask</button></div></details></div>) : <div className="empty-state"><h2>No tasks yet.</h2><p>Create your first task.</p></div>}{archivedTasks.length > 0 && <><div className="section-head archive-head"><h2>Archived</h2></div>{archivedTasks.map((task) => <div className="task task-row" key={task.id}><span>{task.title}</span><button className="text-button" onClick={() => restoreTask(task.id)}>Restore</button></div>)}</>}</Card></AppShell>
}
